spring:
 application:
  name: ServiceRegistory
 cloud:
  config:
   uri: ${CONFIG_SERVER_URL:http://localhost:8888}

server:
 port: 8761

eureka:
 client:
  registerWithEureka: false
  fetchRegistry: false
 server:
  waitTimeWhenSyncEmpty: 0